### ISSUE TITLE
不成功，求指点。

### ISSUE THREAD

**Issue by happlebao** [EraserKing/Unblock163MusicClient#1]
os: win10
.net: 4.6

随笔点几首，都是这个样子的 log
![CIL info](http://i.imgur.com/ndI0ZN1.png)

然后就是这个错误弹窗
![error](http://i.imgur.com/gmjhs5s.png)

然后就没了。没声音。一直转圈。

**Comment by EraserKing** [comment]
请提供以下信息：
1. 是所有歌曲都无法播放吗？可以尝试别的歌手。
2. 给出的mp3文件的URL可以打开吗？
3. 网页版可以播放吗？
4. 如果是个别歌曲不能播放，请给出名称。

**Comment by happlebao** [comment]
额。。。不好意思。。。最近比较忙。。。
1. 是所有都无法播放
2. 
- m1 开头的是 "video playback aborted due to network error"
- m2 开头的是 "connection timeout"
- m3 开头的是 "access denied"
3. 也不行

**Comment by EraserKing** [comment]
1. 尝试在浏览器中访问给出的MP3文件的URL，正常情况下应该是可以直接播放。如果不可以，请给出对应的URL和错误信息。
2. 对的，0.2版删了一些调试信息，以后会加上调试开关。
3. 是的，不在国内的话可能有影响，建议先挂上VPN试一下。印象里在别的脚本里看到过说法，是网易有针对国外的CDN，但是这个功能还没做。

**Comment by EraserKing** [comment]
加了海外开关，建议重新试一下。
0.3的调试信息可以自己选择开或关了。

**Comment by happlebao** [comment]
成功！！！
十分感谢！！！
建议 release 的时候名字取成 Unblock163MusicClient-0.3 而不是 Release-0.3.

**Comment by EraserKing** [comment]
好的 感谢你的建议
