### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by bin456789** [EraserKing/Unblock163MusicClient#2]
switch (bitrate)
            {
                case "96000":
                    return "bMusic";

                case "128000":
                    return "lMusic";

                case "192000":
                    return "bMusic";      //"mMusic"?

                case "320000":
                    return "hMusic";
            }
            return "hMusic";

**Comment by EraserKing** [comment]
Yes you are right. I made a mistake. Would be fixed in next release. Thanks!
