### ISSUE TITLE
下载音乐时提示“下载失败”

### ISSUE THREAD

**Issue by blackyau** [EraserKing/Unblock163MusicClient#7]
1.操作系统：windows7 旗舰版 SP1
2.http://music.163.com/#/m/song?id=27969800
3.同一歌手的http://music.163.com/#/m/song?id=29747640 也能够复现该问题
4.抱歉我看不懂这个条目什么意思...

我的网络为电信，首选DNS：119.29.29.29 备选DNS：168.95.1.1
![qq 20161002135534](https://cloud.githubusercontent.com/assets/14013990/19018999/0a76c438-88a8-11e6-8f63-2caf6c3fcd16.png)
![qq 20161002135617](https://cloud.githubusercontent.com/assets/14013990/19018998/09aa414c-88a8-11e6-8d0d-ea21eaee60a6.png)

**Comment by EraserKing** [comment]
Not maintained now. Closing.
